# Problem 1

In [7]:
# Create numpy arrays a, b, and c by reading the CSV files (a from a.txt, etc.); 
#set their type as dtype = int. 
#Print each one.

import numpy as np
a = np.loadtxt('a.txt', delimiter=',')
print(a)

b = np.loadtxt('b.txt', delimiter=',')
print(b)

c = np.loadtxt('c.txt', delimiter=',')
print(c)

[[ 2.  1.  0.  2.]
 [ 5. -1.  2.  1.]
 [ 1.  0.  1.  1.]
 [ 3.  2.  2.  3.]]
[[ 2. -1.]
 [ 1. -1.]
 [ 2.  2.]
 [-1.  3.]]
[[ 3.  2.]
 [-2.  0.]]


In [8]:
#b. Print the shape of the three arrays, with labels, as in: 'Shape of a is 4x4' (hint: the shape is a tuple).

print('Shape of a is', a.shape)
print('Shape of b is', b.shape)
print('Shape of c is', c.shape)

Shape of a is (4, 4)
Shape of b is (4, 2)
Shape of c is (2, 2)


In [9]:
#c. Print the results of multiplying (using the "real" linear algebra multiplication function, dot( ) ) of a times b, b times c, and b transpose times a.

print(np.dot(a,b))
print(np.dot(b,c))
print(np.dot(b.T,a))


[[ 3.  3.]
 [12.  3.]
 [ 3.  4.]
 [ 9.  8.]]
[[ 8.  4.]
 [ 5.  2.]
 [ 2.  4.]
 [-9. -2.]]
[[ 8. -1.  2.  4.]
 [ 4.  6.  6.  8.]]


In [10]:
#d. Save a, b, and c to binary files. 
#Read those files back into new arrays anew, bnew, and cnew. 
#Print a == anew and the same for bnew and cnew, as proof that your binary read/write is correct.

np.save('a.npy', a)
np.save('b.npy', b)
np.save('c.npy', c)

anew = np.load('a.npy')
bnew = np.load('b.npy')
cnew = np.load('c.npy')

print(a == anew)


[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [11]:
#e. Create array d by reshaping a to be 2 by 8; 
#print it; print its shape with a label. 
#Create array e by reshaping a to be 8 by 2; 
#print it; print its shape with a label.

d = a.reshape(2,8)
print(d)
print('Shape of d is', d.shape)
e = a.reshape(8,2)
print(e)
print('Shape of e is', e.shape)

[[ 2.  1.  0.  2.  5. -1.  2.  1.]
 [ 1.  0.  1.  1.  3.  2.  2.  3.]]
Shape of d is (2, 8)
[[ 2.  1.]
 [ 0.  2.]
 [ 5. -1.]
 [ 2.  1.]
 [ 1.  0.]
 [ 1.  1.]
 [ 3.  2.]
 [ 2.  3.]]
Shape of e is (8, 2)


# Problem 2

In [ ]:
#new fox population = (fox growth factor)*old fox population + (eat chickens rate)*old chicken population, 
# new chicken population = (kill rate)*old fox population + (chicken growth factor)*old chicken population

In [ ]:
## Getting input
f = float(input("Enter the fox growth rate: ")) #0.6

c = float(input("Enter the chicken growth rate: ")) #1.2

e= float(input("Enter the eat-chicken rate: ")) #0.5

k = float(input("Enter kill rate: ")) #0.5

iter = int(input("Enter number of iterations: ")) #2

#print the time period, chicken and fox population 

print('{:<20} {:<15} {:<15}'.format('Time period', '# foxes', '# chickens'))

print()

## calculate the result of somulation for i times
fox = 100
chicken = 1000
print('{:<20} {:<15} {:<15}'.format(0, fox, chicken))

for i in range(iter):
    result = np.array([[f, e], [-k, c]]).dot(np.array([fox, chicken]))
    fox = result[0]
    chicken = result[1]
    print('{:<20} {:<15} {:<15}'.format(i, fox, chicken))

# for j in range(i):
#     fox = f*fox + e*chicken
#     chicken = k*fox + c*chicken
#     print("After", j+1, "iterations, the fox population is", fox, "and the chicken population is", chicken)


In [40]:
print('{:<20} {:<15} {:<15}'.format('Time period', '# foxes', '# chickens'))

Time period          # foxes         # chickens     


In [ ]:
Time period
0
1
2

100
560
931
# chickens
1000
1190
1372

In [29]:
import numpy as np
f = 0.6
c = 1.2
e = 0.5
k = 0.8

fox = 100
chicken = 1000