# Lab 3

## Problem 1

In [1]:
#Create a list variable named numbers and set it to the integers -5 to 5 inclusive
numbers = list(range(-5,6))

#Save the contents of numbers to a text file named 'numbers.txt', one int per line
with open('numbers.txt', 'w') as f:
    for i in numbers:
        f.write('%d\n' % (i))   


# Problem 2

In [2]:
#Create a list variable named myNums. 
myNums = []
#Open 'numbers.txt' for reading and read the line and convert it to int, one at a time, into myNums. 
with open('numbers.txt', 'r') as f:
    for line in f:
        myNums.append(int(line))

# Display the list.
print (myNums)
#  Then use print(numbers == myNums) to verify that it has the same int as numbers in #1.
print(numbers == myNums)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
True


# Problem 3

In [3]:
#Use the following list of tuples named data for this problem. 
#Display data. Then open a file named 'mydata.bin' with 'wb' access. 
# Write data to this file using pickle (don't forget to do import pickle). 
# Open the file in a text editor (or use the alternatives in #1).
data = [('Fido', 12), ('Barfy', 8), ('Spot', 5), ('Yeller', 15)]
import pickle

print(data)

with open('mydata.bin', 'wb') as f:
    pickle.dump(data, f)

[('Fido', 12), ('Barfy', 8), ('Spot', 5), ('Yeller', 15)]


# Problem 4

In [4]:
# Open the file 'mydata.bin' with 'rb' access. 
# Use pickle to read its contents into a variable named newdata.
with open ('mydata.bin', 'rb') as f:
    newdata = pickle.load(f)
 
#Display the type of newdata to verify that it is a list. 
print(type(newdata))
# Then display newdata and use print(data == newdata) to verify that the data is the same in #5
print(newdata == data)

<class 'list'>
True


# Problem 5

In [6]:
import numpy as np

In [9]:
# (a.) Create numpy arrays named x, y, N, and I as:
# x: the floats from 1 to 3 counting by 0.5; use arange( ), but reshape it to (4,1) 
# y: from the list [-1.0, 1.0, -1.0, 1.0], but reshape it to (4,1)
# N: from the list of lists [ [0, 1, 1, 0], [3, 2, 1, 0] ]
# I: the 4x4 identity matrix

x = np.arange(1,3,0.5).reshape(4,1)
y = np.array([-1.0, 1.0, -1.0, 1.0]).reshape(4,1)
N = np.array([[0, 1, 1, 0], [3, 2, 1, 0]])
I = np.identity(4)



# (b.) Display each array.
print(x)
print(y)
print(N)
print(I)

# (c.) Display each array's shape (size)
print(x.shape)
print(y.shape)
print(N.shape)
print(I.shape)

# (d.) Display each array's dimensionality (ndim) 
print(x.ndim)
print(y.ndim)
print(N.ndim)
print(I.ndim)

# (e.) Display N's zeroth row using a slice
print(N[0]) 

# (f.) Display N's zeroth column using a slice
print(N[:,0])

[[1. ]
 [1.5]
 [2. ]
 [2.5]]
[[-1.]
 [ 1.]
 [-1.]
 [ 1.]]
[[0 1 1 0]
 [3 2 1 0]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 1)
(4, 1)
(2, 4)
(4, 4)


# Problem 6

In [25]:
#  For each problem, tell which operations are legal - *before* entering them. Then execute and print them. 
# (a.) x+y
print(x+y)


# (b.) x*y
print(x*y)
# (c.) x.dot(y) ## Not LEGAL, dimention does not match
# print(x.dot(y))

# (d.) (x.T).dot(y) 
print((x.T).dot(y))

#(e.) x.dot(y.T) 
print(x.dot(y.T))

# (f.) N*N
print(N*N)
# (g.) x*N
# print(x*N) NOT LEGAL, dimention does not match

# (h.) x.dot(N) 
# print(x.dot(N)) not legal, dimention does not match

# (i.) (x.T).dot(N) 
#print((x.T).dot(N)) not legal, dimention does not match
# (j.) N.dot(x)
print(N.dot(x))

[[0. ]
 [2.5]
 [1. ]
 [3.5]]
[[-1. ]
 [ 1.5]
 [-2. ]
 [ 2.5]]
[[1.]]
[[-1.   1.  -1.   1. ]
 [-1.5  1.5 -1.5  1.5]
 [-2.   2.  -2.   2. ]
 [-2.5  2.5 -2.5  2.5]]
[[0 1 1 0]
 [9 4 1 0]]
[[3.5]
 [8. ]]


In [22]:
print((x.shape,N.shape))

((4, 1), (2, 4))


In [23]:
print(x.dot(N))

ValueError: shapes (4,1) and (2,4) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
for i in numbers:
    #Save the contents of numbers to a text file named 'numbers.txt', one int per line – that is, open a file with 'w' permission and use
    f.write('%d\n' % (i))